### ISSUE TITLE
Typing in the text fields does not work in Firefox

### ISSUE THREAD

**Issue by bootmii** [maxwellpollack/scalemap#1]
![image](https://user-images.githubusercontent.com/6440426/110613304-f8184a00-8145-11eb-8bb2-1437d009f9f1.png)
I don't know how you solved the problem with the hyphen/semicolon/equals (inaudibly high by default, but presumably) keys that everyone else seems to be having in Firefox.

**Comment by ellamenop** [comment]
Closing because this is a [duplicate issue](https://github.com/maxwellpollack/frex/issues/1).
