### ISSUE TITLE
C/C++ API problem

### ISSUE THREAD

**Issue by bgmsadoques-professional** [maxwellpollack/scalemap#2]
Delete line 778 in the header file. The line 
#include "tinyexpr.h"
prevents compilation, since tinyexpr.h does not exist and is embedded in the header file.

**Comment by shapnesht** [comment]
@bgmsadoques-professional 
can I work on this issue?

**Comment by ellamenop** [comment]
Thanks for pointing this out! Fixed in https://github.com/maxwellpollack/scalemap/commit/c90054492910287d94d6d7509f802e2ea902dc4a
